StudioMooMooPortal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse
from django.template import loader

def homepage_view(request):
    """
    Render the index page
    """
    template = loader.get_template('index.html')
    return HttpResponse(template.render({}, request))

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path('summernote/', include('django_summernote.urls')),
    path("", include("booking.urls"), name='booking-urls')
]

booking/urls.py
from django.urls import path
from . import views

app_name = 'booking'
urlpatterns = [
    path("", views.home, name='home'),
    path("booking/", views.booking, name='booking'),
    path('my_bookings/', views.my_bookings, name='my_bookings'),
    path('edit_booking/<int:booking_id>',
         views.edit_booking, name='edit_booking'),
    path('delete_booking/<int:booking_id>',
         views.delete_booking, name='delete_booking'),
    path('success_booking/<int:booking_id>',
         views.success_booking, name='success_booking'),
]

booking/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Booking(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    artist_name = models.CharField(max_length=30)
    date = models.DateField()
    booking_requirements = models.CharField(max_length=700)

    def __str__(self):
        return self.artist_name

booking/forms.py
from django import forms
from django.forms.widgets import DateInput
from django.core.exceptions import ValidationError
from datetime import datetime, date
from .models import Booking


class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ('artist_name', 'date', 'booking_requirements')
        widgets = {
            'artist_name': forms.Textarea(attrs={'cols': 60, 'rows': 1}),
            'date': DateInput(attrs={'type': 'date'}),
            'booking_requirements': forms.Textarea()
        }

    def clean(self):
        """
        Custom validation to ensure date and time are valid and available
        """
        cleaned_data = super().clean()
        date = cleaned_data.get("date")

        if date < date.today():
            raise ValidationError("Please select a date in the future.")

        existing_bookings = Booking.objects.filter(
            date=date).exclude(id=self.instance.id)
        print('existing_bookings', existing_bookings)

        if existing_bookings:
            raise ValidationError(
                "That date is already taken, "
                "please select a different date."
            )

booking/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.urls import reverse
from django.views import generic
from django.http import HttpResponseRedirect
from django.contrib import messages
from .models import *
from .forms import *


# Create your views here.
def home(request):
    return render(request, "index.html")


def booking(request):
    return render(request, "booking/booking.html")


def my_bookings(request):
    bookings = Booking.objects.filter(user=request.user)
    booking_form = BookingForm()
    if request.method == "POST":
        booking_form = BookingForm(data=request.POST)
        if booking_form.is_valid():
            booking = booking_form.save(commit=False)
            booking.user = request.user
            booking.save()
            print('booking id', booking.id)
            return redirect(reverse('booking:success_booking',
                            args=[booking.id]))

    return render(
        request,
        "booking/booking_list.html",
        {
            'booking_form': booking_form,
            'bookings': bookings,
        },
        )


def edit_booking(request, booking_id):
    # view to edit booking
    queryset = Booking.objects.all()
    booking = get_object_or_404(queryset, pk=booking_id)
    booking_form = BookingForm(instance=booking)

    if request.method == "POST":
        queryset = Booking.objects.all()
        booking = get_object_or_404(queryset, pk=booking_id)
        booking_form = BookingForm(data=request.POST, instance=booking)

        if booking_form.is_valid():
            booking = booking_form.save()
            messages.add_message(request, messages.SUCCESS, 'Booking Updated!')
            return redirect(reverse('booking:my_bookings'))
        else:
            messages.add_message(request, messages.ERROR,
                                 'Error updating booking!')
    return render(
        request,
        "booking/booking_edit.html",
        {
            'booking_form': booking_form,
        },
    )


def delete_booking(request, booking_id):
    """
    view to delete booking
    """
    booking = get_object_or_404(Booking, pk=booking_id)

    if request.method == 'POST':
        booking.delete()
        messages.add_message(request, messages.SUCCESS, 'Booking Deleted!')
        return redirect(reverse('booking:my_bookings'))
    else:
        return render(
            request,
            "booking/booking_delete.html",
            {
                'booking': booking,
            },
            )


def success_booking(request, booking_id):
    """
    Success page after making a booking
    """
    booking = get_object_or_404(Booking, pk=booking_id)

    if request.method == 'POST':
        messages.add_message(request, messages.SUCCESS, 'Booking created!')
        return redirect(reverse('booking:success_booking', args=[booking.id]))
    else:
        return render(
            request,
            "booking/booking_success.html",
            {
                'booking': booking,
            },
            )

booking/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
        Django App
      {% endblock %}
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"  rel="stylesheet" />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">My Django App</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">{% block content %} {% endblock %}</div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" ></script>
  </body>
</html>

booking/templates/booking/booking_delete.html
{% extends "base.html" %} {% block title %} Studio Moo Moo {% endblock %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}



<div class="container mx-5 my-5">
  <div class="row">
    <div class="col-sm">
      <main class="flex-shrink-0 main-bg">
        {% if user.is_authenticated %}
        <p class="text-end m-3">You are logged in as: {{ user }}</p>
        {% else %}
        <p class="text-end m-3">You are not logged in</p>
        {% endif %}
        <div>
          <h1>Delete a Booking</h1>
          <div class="col-md-4 mb-4 mt-3">
            <div>
              {% if user.is_authenticated %}
              <form id="bookingForm" method="post" style="margin-top: 1.3em;">
                {% csrf_token %}
                <h3> Are you sure you want to delete the following booking ?</h3>
                <h4>{{ booking.artist_name }} -- {{ booking.date }}</h4>
                <button id="BookingButton" type="submit" class="btn btn-lg btn-light">Delete Booking</button>
                <a href="{% url 'booking:delete_booking' booking.pk%}"></a>
                  <a href="{% url 'booking:my_bookings'%}" class="btn btn-lg btn-light">Cancel</a>

              </form>
              {% else %}
              <p>Log in to make a booking</p>
              {% endif %}
            </div>
          </div>
        </div>
      </main>
    </div>
  </div>
</div>
{% endblock %}

booking/templates/booking/booking_edit.html
{% extends "base.html" %} {% block title %} Studio Moo Moo {% endblock %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
  <div class="flex-shrink-0 main-bg">
    {% if user.is_authenticated %}
    <p class="text-end m-3">You are logged in as: {{ user }}</p>
    {% else %}
    <p class="text-end m-3">You are not logged in</p>
    {% endif %}
  </div>
  <div>
    <h1>Edit a Booking</h1>
    <div class="col-md-4 mb-4 mt-3">
      <div>
        {% if user.is_authenticated %}
        <form id="bookingForm" method="post" style="margin-top: 1.3em;">
          {{ booking_form | crispy }}
          {% csrf_token %}
          <button id="BookingButton" type="submit" class="btn btn-lg btn-light">Save Booking</button>
          <button id="CancelButton" type="submit" class="btn btn-lg btn-light">Cancel Editing</button>
        </form>
        {% else %}
        <p>Log in to make a booking</p>
        {% endif %}
      </div>
    </div>
  </div>

</div>
{% endblock %}

booking/templates/booking/booking_list.html
{% extends "base.html" %} {% block title %} Studio Moo Moo {% endblock %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}


<section>
  <div class="container">
    <div class="row">
      <div class="flex-shrink-0 main-bg">
        {% if user.is_authenticated %}

        {% else %}
        <p class="text-end m-3">You are not logged in</p>
        {% endif %}
      </div>
      <div class="container">
        <h1>Make a new Booking</h1>
        <div class="col-md-6 mb-4 mt-3">
          <div>
            {% if user.is_authenticated %}
            <form id="bookingForm" method="post" style="margin-top: 1.3em;">
              {{ booking_form | crispy }}
              {% csrf_token %}
              <button id="BookingButton" type="submit" class="btn btn-lg btn-light">Make A Booking</button>
            </form>
            {% else %}
            <p>Log in to make a booking</p>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div>
      <h1>Existing bookings for {{ user }}</h1>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Artist Name</th>
          <th scope="col">Date</th>
          <th scope="col">Requirements</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      {% for booking in bookings %}
      <tbody>
        <tr>
          <th scope="row">{{ booking.artist_name }}</th>
          <td>{{ booking.date }}</td>
          <td>{{ booking.booking_requirements }}</td>
          {% if user.is_authenticated %}
          <td>
            <a class="btn btn-light btn-edit" href="{% url 'booking:edit_booking' booking.pk%}">Edit</a>
          <td>
            <a class="btn btn-light btn-edit" href="{% url 'booking:delete_booking' booking.pk%}">Delete</a></td>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</section>

{% endblock %}

{% block extras %}
<script src="{% static 'js/bookings.js' %}"></script>
{% endblock %}

booking/templates/booking/booking_success.html
{% extends "base.html" %} {% block title %} Studio Moo Moo {% endblock %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}



<div class="container mx-5 my-5">
  <div class="row">
    <div class="col-sm">
      <main class="flex-shrink-0 main-bg">
        {% if user.is_authenticated %}
        <p class="text-end m-3">You are logged in as: {{ user }}</p>
        {% else %}
        <p class="text-end m-3">You are not logged in</p>
        {% endif %}
        <div>
          <h1>Your booking is Successful</h1>
          <div class="col-md-4 mb-4 mt-3">
            <div>
              {% if user.is_authenticated %}
              <form id="bookingForm" method="post" style="margin-top: 1.3em;">
                {% csrf_token %}
                <h3> Booking Successfull</h3>
                <h4>{{ booking.artist_name }} -- {{ booking.date }}</h4>
                <a href="{% url 'booking:my_bookings'%}" class="btn btn-lg btn-light">Back to Bookings</a>
              </form>
              {% else %}
              <p>Log in to make a booking</p>
              {% endif %}
            </div>
          </div>
        </div>
      </main>
    </div>
  </div>
</div>

{% endblock %}

templates/base.html
{% load static %}

{% url 'home' as home_url %}
{% url 'account_login' as login_url %}
{% url 'account_signup' as signup_url %}
{% url 'account_logout' as logout_url %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    {% block title %}
    Studio Moo Moo
    {% endblock %}
  </title>
  <!--Bootstrap CSS-->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <!-- Custom CSS -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>

<!-- navbar -->
<body>
  <nav class="navbar navbar-custom navbar-expand-lg navbar-light bg-dark fixed-top">
    <a class="navbar-brand" href="{% url 'booking:home' %}">
      <img src="{% static 'images/SMM_logotext_WHT_THK_TRANS.png' %}" width="200" id="image-logo"
        alt="Studio Moo Moo Logo">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'booking:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'booking:home' %}#about">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'booking:home' %}#gallery">Gallery</a>
        </li>

        {% if user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'booking:my_bookings' %}">Bookings <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == logout_url %}active{% endif %}" aria-current="page"
            href="{% url 'account_logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link {% if request.path == login_url %}active{% endif %}" aria-current="page"
            href="{% url 'account_login' %}">Register/Login</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>
  <div class="container top-buffer">
    <div class="container">
      <div class="row">
        <div class="col-md-8 offset-md-2">
          {% for message in messages %}
          <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
            {{ message | safe }}
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
  

{% block content %}
<!-- Content Goes here -->
{% endblock content %}

  <!-- footer -->
  <footer class="footer mt-auto py-3 dark-bg">
    <p class="m-0 text-center text-white">© 2024 Copyright: Studio Moo Moo</p>
    <p class="m-0 text-center text-white">Follow us:
      <a data-mdb-ripple-init class="btn text-white btn-floating m-1" style="background-color: #3b5998;"
        href="https://www.facebook.com/" role="button"><i class="fab fa-facebook-f" aria-hidden="true"></i><span class="sr-only">Link to our Facebook page</span></a>
      <a data-mdb-ripple-init class="btn text-white btn-floating m-1" style="background-color: #ac2bac;"
        href="https://www.instagram.com" role="button"><i class="fab fa-instagram"></i><span class="sr-only">Link to our Instagram page</span></a>
      <a data-mdb-ripple-init class="btn text-white btn-floating m-1" style="background-color: black;"
        href=https://www.x.com/ role="button"><i class="fab fa-x-twitter"></i><span class="sr-only">Link to our X page</span></a>
    </p>
  </footer>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
  <!--Font Awesome Kit-->
  <script src="https://kit.fontawesome.com/1e7673fa14.js" crossorigin="anonymous"></script>
  <script>
    $("#copyright").text(new Date().getFullYear());
  </script>

  {% block extras %}
  {% endblock extras %}
</body>



</html>

templates/index.html
{% extends "base.html" %} {% block title %} Studio Moo Moo {% endblock %}
{% load static %}

{% block content %}

<div class="hero container-fluid"> 
  <img class='img-fluid w-100' src="{% static 'images/gallery/stone.webp' %}" style="width:100%" alt="stone wall">
  <div class="container">
    <div class="heroLogo centerLogo" >
      <img id="logo" src="{% static 'images/SMM_logotext_WHT_THK_TRANS.png' %}" class="img-fluid d-block" alt="Studio Moo Moo logo">
        <div class="callToAction">
          <a id="make_booking" href="{% url 'account_login' %}" class="btn btn-light btn-lg m-5 mx-auto">Click to make booking</a>
        </div>
    </div>
  </div>
</div>

<div id="about" class="introText row mt-2 mb-lg-4">
    <div class="col-md-8 mx-auto">
        <div class="w-100 px-5 py-4 members   text-center mt-5">
            <h1>Boutique Recording facility in the northwest of ireland</h1>
            <p>
                Welcome to Studio Moo Moo, an idyllic recording haven in rural north-west Ireland, just a short drive from Dublin and Knock international Airport. This 16-track studio, a labour of love by creator Mat Warren, offers a retreat for intimate songwriting and recording. Its one-room design seamlessly integrates live tracking with fostering a fluid creative process. Meticulous attention to lighting, decor, and top-notch acoustic design creates a cozy and inspiring atmosphere. Whether you're a solo artist or a group, Studio Moo Moo provides the perfect backdrop for your musical journey in the serene landscapes of rural Ireland.
            </p>
        </div>
    </div>
</div>
<!-- divider -->
<div class="row justify-content-center">
  <hr class="col-8 mt-5 mb-4 mb-lg-5">
</div>
<!-- divider -->

<!-- Gallery -->
<div id="gallery" class="row mb-lg-4">
  <div class="col-md-8 mx-auto">
      <div class="w-100 px-5 py-4 members text-center mt-5">
          <h1>Gallery</h1>
          <p>
            A selection of images from the studio
          </p>
      </div>
  </div>
</div>

<div id="gallery-photos" class="row mb-5">
  <div class="col-lg-3 col-md-12 mb-lg-0">
    <img
      src="{% static 'images/gallery/cables.webp' %}"
      class="w-100"
      alt="Cables on wall"
    >

    <img
      src="{% static 'images/gallery/amps.webp' %}"
      class="w-100"
      alt="Amplifiers against wall"
    >
  </div>

  <div class="col-lg-3 mb-lg-0">
    <img
      src="{% static 'images/gallery/pbass.webp' %}"
      class="w-100"
      alt="Fender bass on a stone wall"
    >

    <img
      src="{% static 'images/gallery/modular.webp' %}"
      class="w-100"
      alt="Modular synths in case"
    >

    <img
    src="{% static 'images/gallery/roof1.webp' %}"
    class="w-100"
    alt="uplit wooden slats on studio roof"
    >
  </div>

  <div class="col-lg-3 mb-lg-0">
    <img
      src="{% static 'images/gallery/upsteps.webp' %}"
      class="w-100"
      alt="Looking up wooden steps bookshelf"
    >

    <img
      src="{% static 'images/gallery/drums.webp' %}"
      class="w-100"
      alt="Drumkit in recording studio"
    >
  </div>

  <div class="col-lg-3 mb-lg-0">
    <img
      src="{% static 'images/gallery/sofa.webp' %}"
      class="w-100"
      alt="sofa in studio attic space"
    >

    <img
      src="{% static 'images/gallery/roof.webp' %}"
      class="w-100"
      alt="wooden slats on studio roof"
    >

    <img
    src="{% static 'images/gallery/fenderamp.webp' %}"
    class="w-100"
    alt="Fender princeton amplifier"
  >
  </div>


</div>


{% endblock %}

templates/mfa/authenticate.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Sign In" %}
{% endblock head_title %}
{% block content %}
    <h1>{% trans "Two-Factor Authentication" %}</h1>
    <p>
        {% blocktranslate %}Your account is protected by two-factor authentication. Please enter an authenticator code:{% endblocktranslate %}
    </p>
    <form class="authenticate"
          method="POST"
          action="{% url 'mfa_authenticate' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Sign In" %}</button>
    </form>
{% endblock content %}

templates/mfa/index.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Two-Factor Authentication" %}
{% endblock head_title %}
{% block content %}
    <h1>{% trans "Two-Factor Authentication" %}</h1>
    <section class="totp">
        <h2>{% translate "Authenticator App" %}</h2>
        {% if authenticators.totp %}
            <p>{% translate "Authentication using an authenticator app is active." %}</p>
            <ul class="actions">
                <li>
                    <a href="{% url 'mfa_deactivate_totp' %}">{% translate "Deactivate" %}</a>
                </li>
            </ul>
        {% else %}
            <p>{% translate "An authenticator app is not active." %}</p>
            <ul class="actions">
                <li>
                    <a href="{% url 'mfa_activate_totp' %}">{% translate "Activate" %}</a>
                </li>
            </ul>
        {% endif %}
    </section>
    <section class="recovery_codes">
        <h2>{% translate "Recovery Codes" %}</h2>
        {% if authenticators.recovery_codes %}
            <p>
                {% blocktranslate with total_count=authenticators.recovery_codes.generate_codes|length count unused_count=authenticators.recovery_codes.get_unused_codes|length %}There is {{ unused_count }} out of {{ total_count }} recovery codes available.{% plural %}There are {{ unused_count }} out of {{ total_count }} recovery codes available.{% endblocktranslate %}
            </p>
            <ul class="actions">
                <li>
                    <a href="{% url 'mfa_view_recovery_codes' %}">{% translate "View codes" %}</a>
                </li>
                <li>
                    <a href="{% url 'mfa_download_recovery_codes' %}">{% translate "Download codes" %}</a>
                </li>
                <li>
                    <a href="{% url 'mfa_generate_recovery_codes' %}">{% translate "Generate new codes" %}</a>
                </li>
            </ul>
        {% else %}
            <p>{% translate "No recovery codes set up." %}</p>
        {% endif %}
    </section>
{% endblock content %}

templates/mfa/recovery_codes/base.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Recovery Codes" %}
{% endblock head_title %}

templates/mfa/recovery_codes/generate.html
{% extends "mfa/recovery_codes/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% translate "Recovery Codes" %}</h1>
    <p>
        {% blocktranslate %}You are about to generate a new set of recovery codes for your account. This action will invalidate your existing codes. Are you sure?{% endblocktranslate %}
    </p>
    <form method="POST" action="{% url 'mfa_generate_recovery_codes' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Generate" %}</button>
    </form>
{% endblock content %}

templates/mfa/recovery_codes/index.html
{% extends "mfa/recovery_codes/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% translate "Recovery Codes" %}</h1>
    <p>
        {% blocktranslate count unused_count=unused_codes|length %}There is {{ unused_count }} out of {{ total_count }} recovery codes available.{% plural %}There are {{ unused_count }} out of {{ total_count }} recovery codes available.{% endblocktranslate %}
    </p>
    {% if unused_codes %}
        <textarea class="recovery-codes" rows="{{ unused_codes|length }}" readonly>{% for code in unused_codes %}{{ code }}
{% endfor %}
</textarea>
    {% endif %}
    <ul class="actions">
        {% if unused_codes %}
            <li>
                <a href="{% url 'mfa_download_recovery_codes' %}">{% translate "Download codes" %}</a>
            </li>
        {% endif %}
        <li>
            <a href="{% url 'mfa_generate_recovery_codes' %}">{% translate "Generate new codes" %}</a>
        </li>
    </ul>
{% endblock content %}

templates/mfa/totp/activate_form.html
{% extends "mfa/totp/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% trans "Activate Authenticator App" %}</h1>
    {{ totp_svg|safe }}
    <form method="POST" action="{% url 'mfa_activate_totp' %}">
        {% csrf_token %}
        <p>
            <label>{% translate "Authenticator secret" %}:</label>
            <input type="text"
                   disabled="disabled"
                   value="{{ form.secret }}"
                   size="{{ form.secret|length }}">
        </p>
        {{ form.as_p }}
        <button type="submit">{% trans "Activate" %}</button>
    </form>
{% endblock content %}

templates/mfa/totp/base.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Authenticator App" %}
{% endblock head_title %}

templates/mfa/totp/deactivate_form.html
{% extends "mfa/totp/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% trans "Deactivate Authenticator App" %}</h1>
    <p>
        {% blocktranslate %}You are about to deactivate authenticator app based authentication. Are you sure?{% endblocktranslate %}
    </p>
    <form method="POST" action="{% url 'mfa_deactivate_totp' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Deactivate" %}</button>
    </form>
{% endblock content %}